### ISSUE TITLE
Unknown classes, functions, variables in execute cause uninformative failure

### ISSUE THREAD

**Issue by dkornishev** [Dreckr/Worker#7] opened 2014-06-14 16:11 UTC
``` dart
Future execute() {
    run = a; // boom
  }
```

In normal context, runtime issues a helpful message saying variables/classes/functions are not found.

When running via worker:
`Illegal argument(s): Illegal argument in isolate message : (object is a stacktrace)`

**Comment by Dreckr** [comment] 2014-06-14 17:14
Hi, Danil! Thanks for reporting.

The problem is that Dart does not allow stacktraces to be passed in Isolate messages and Errors have stacktraces attached to them (where Exceptions do not). What I can do is stringify the stackTrace and the error message, wrap them around an object and pass them back.

**Comment by Dreckr** [comment] 2014-06-14 17:54
There's a library called 'stack_trace' that allows stackTrace manipulation. Using it I was able to make stackTraces serializable.

This bug is fixed on 0.3.9! Cheers!

**Closed as completed by Dreckr** 2014-06-14 17:54 UTC
Labels: bug

**Comment by dkornishev** [comment] 2014-06-14 18:31
Nice!  Yeah, dart is weird on what it allows to go cross isolates.  I would
love for functions to be passable, but alas
